# Generated by Django 4.2.1 on 2023-05-24 10:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadejte jméno autora', max_length=80, verbose_name='Jméno autora')),
                ('prijmeni', models.CharField(help_text='Zadejte příjmení autora', max_length=80, verbose_name='Příjmení autora')),
                ('rok_narozeni', models.IntegerField(help_text='Zadejte rok narození autora', validators=[django.core.validators.MinValueValidator(0, message='Hodnota musí být větší nebo rovna 0.'), django.core.validators.MaxValueValidator(2023, message='Hodnota musí být menší nebo rovna 2023.')], verbose_name='Rok narození autora')),
                ('rok_umrti', models.IntegerField(help_text='Zadejte rok úmrtí autora', validators=[django.core.validators.MinValueValidator(0, message='Hodnota musí být větší nebo rovna 0.'), django.core.validators.MaxValueValidator(2023, message='Hodnota musí být menší nebo rovna 2023.')], verbose_name='Rok úmrtí autora')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autori',
                'ordering': ['jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Mistnosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_mistnosti', models.IntegerField(help_text='Zadejte číslo místnosti', verbose_name='Číslo místnosti')),
                ('podlazi', models.CharField(choices=[('Přízemí', 'Přízemí'), ('1.patro', '1.patro'), ('2. patro', '2. patro'), ('Neznámé', 'Neznámé')], default='Neznámé', help_text='Zadejte podlaží místnosti', max_length=10, verbose_name='Podlaží')),
            ],
            options={
                'verbose_name': 'Mistnost',
                'verbose_name_plural': 'Mistnosti',
                'ordering': ['podlazi'],
            },
        ),
        migrations.CreateModel(
            name='Obrazy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název obrazu', max_length=80, verbose_name='Název obrazu')),
                ('popis', models.TextField(blank=True, help_text='Zadejte popis obrazu', max_length=4000, null=True)),
                ('autor', models.ForeignKey(help_text='Zadejte jméno autora', on_delete=django.db.models.deletion.CASCADE, to='galeriedb.autori', verbose_name='Jméno autora')),
                ('mistnost', models.ForeignKey(help_text='Zadejte číslo místnosti', on_delete=django.db.models.deletion.CASCADE, to='galeriedb.mistnosti', verbose_name='Číslo místnosti')),
            ],
            options={
                'verbose_name': 'Obraz',
                'verbose_name_plural': 'Obrazy',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Vystava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název výstavy', max_length=80, verbose_name='Název výstavy')),
                ('popis', models.TextField(blank=True, help_text='Zadejte popis výstavy', max_length=4000, null=True)),
                ('mistnosti', models.ManyToManyField(help_text='Zadejte číslo místnosti', to='galeriedb.mistnosti', verbose_name='Čísla místností')),
                ('obrazy', models.ManyToManyField(help_text='Zadejte obrazy na výstavě', to='galeriedb.obrazy', verbose_name='Obrazy na výstavě')),
            ],
            options={
                'verbose_name': 'Vystava',
                'verbose_name_plural': 'Vystavy',
                'ordering': ['nazev'],
            },
        ),
    ]
