# Generated by Django 4.2.1 on 2023-05-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistnosti',
            name='podlazi',
            field=models.CharField(choices=[('Přízemí', 'Přízemí'), ('1. patro', '1. patro'), ('2. patro', '2. patro'), ('Neznámé', 'Neznámé')], default='Neznámé', help_text='Zadejte podlaží místnosti', max_length=10, verbose_name='Podlaží'),
        ),
    ]
