# Generated by Django 4.2.1 on 2023-05-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeriedb', '0002_alter_mistnosti_podlazi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mistnosti',
            options={'ordering': ['cislo_mistnosti'], 'verbose_name': 'Mistnost', 'verbose_name_plural': 'Mistnosti'},
        ),
    ]
