# Generated by Django 4.2.1 on 2023-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriedb', '0003_alter_mistnosti_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrazy',
            name='fotka',
            field=models.ImageField(blank=True, help_text='Přidejte fotku', null=True, upload_to='obrazy', verbose_name='Fotka'),
        ),
        migrations.AddField(
            model_name='vystava',
            name='fotka',
            field=models.ImageField(blank=True, help_text='Přidejte fotku', null=True, upload_to='vystavy', verbose_name='Fotka'),
        ),
    ]
